/**
 * Reusable React Hook to interact with Schema.org CreativeWork entity in the VKG.
 * Auto-generated by Hygen.
 */
import { createSemanticHook } from '@pcp/data';
import { CreativeWork } from '../types/semantic/CreativeWork';

export const useCreativeWork = createSemanticHook<CreativeWork>('https://schema.org/CreativeWork');
