/**
 * Reusable React Hook to interact with Schema.org Event entity in the VKG.
 * Auto-generated by Hygen.
 */
import { createSemanticHook } from '@pcp/data';
import { Event } from '../types/semantic/Event';

export const useEvent = createSemanticHook<Event>('https://schema.org/Event');
